# Generated by Django 5.1.7 on 2025-04-03 09:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TTSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_warning_message', models.CharField(blank=True, max_length=255, null=True)),
                ('last_tts_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
