# Generated by Django 5.1.7 on 2025-04-03 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TTSLog',
        ),
    ]
